[build]
builder = "NIXPACKS"
buildCommand = "npm install && npx prisma generate"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
preDeployCommand = ["npx prisma db push --skip-generate"]
